# Generated by Django 6.1.1 on 2026-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('vacancy', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='job/')),
            ],
        ),
    ]
